cookie:
  expiry_days: 30
  key: some_random_key_do_not_share
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: $2b$12$RjVwZ... # The hashed password you generated
    cdoe:
      email: cdoe@example.com
      name: Cathy Doe
      password: $2b$12$ZqN9... # Another hashed password
